language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_install:
  - git remote set-url origin git@github.com:learnxasy/learnxasy.github.io.git
install:
  - npm install
script:
  - npm test
  - npm run deploy